//! Copy Coalescing pass: forwards stores through temporary variables,
//! eliminating redundant copy chains.

use super::common::{
    action_args, clone_var_node, extract_var_value_args, get_variable_name, is_plain_temp,
    is_temp_var, node_str_eq, same_variable,
};
use crate::ir::arena::NodeArena;
use crate::ir::mir::Mir;
use crate::ir::opt::FunctionPass;
use egg::*;
use std::collections::{HashMap, HashSet};

/// Temporary variables for this pass additionally include `__mt` — temporaries
/// generated by `MirLowerer::fresh_temp`.
const TEMP_PREFIXES: &[&str] = &["__mt"];

type NameToId = HashMap<String, Id>;
type NamedTarget = HashMap<String, (String, Id)>;
type ActionWrites = HashMap<String, (Id, usize)>;

struct AliasData {
    action_lets: NameToId,
    aliases: NamedTarget,
    reverse_aliases: NamedTarget,
    alias_lets: NameToId,
}

struct CopyData {
    copies: NamedTarget,
    set_values: NameToId,
    immediately_dead: HashSet<Id>,
}

struct Resolution {
    redirects: NamedTarget,
    dead_lets: HashSet<Id>,
    dead_set_values: HashSet<Id>,
    dead_temps: HashSet<String>,
}

fn find_variable_arg_in_action(expr: &RecExpr<Mir>, action_id: Id) -> Option<(usize, Id)> {
    let args = action_args(expr, action_id)?;
    for (i, &arg_id) in args.iter().enumerate() {
        if let Mir::Named([name_id, value_id]) = &expr[arg_id]
            && node_str_eq(&expr[*name_id], "variable")
        {
            return Some((i, *value_id));
        }
    }
    None
}

fn is_pure_copy_action(expr: &RecExpr<Mir>, id: Id) -> bool {
    let Some(args) = action_args(expr, id) else {
        return false;
    };
    if args.len() != 2 {
        return false;
    }
    let mut has_var = false;
    let mut has_val = false;
    for &arg_id in args {
        if let Mir::Named([name_id, _]) = &expr[arg_id] {
            if node_str_eq(&expr[*name_id], "variable") {
                has_var = true;
            } else if node_str_eq(&expr[*name_id], "value") {
                has_val = true;
            }
        }
    }
    has_var && has_val
}

fn collect_write_counts(expr: &RecExpr<Mir>) -> HashMap<String, usize> {
    let mut counts: HashMap<String, usize> = HashMap::new();
    for (i, node) in expr.as_ref().iter().enumerate() {
        let id = Id::from(i);
        if let Mir::Action(_) = node
            && let Some((_, write_target_id)) = find_variable_arg_in_action(expr, id)
            && let Some(name) = get_variable_name(expr, write_target_id)
        {
            // `local x = line x` is not a self-copy: the scopes differ, and the
            // name alone says nothing.
            if is_pure_copy_action(expr, id)
                && let Some((t_id, v_id)) = extract_var_value_args(expr, id)
                && same_variable(expr, t_id, v_id)
            {
                continue;
            }
            *counts.entry(name.to_string()).or_insert(0) += 1;
        }
    }
    counts
}

fn collect_action_writes(expr: &RecExpr<Mir>) -> ActionWrites {
    let mut actions_by_temp: HashMap<String, Vec<(Id, usize)>> = HashMap::new();
    for (index, node) in expr.as_ref().iter().enumerate() {
        let id = Id::from(index);
        if matches!(node, Mir::Action(_))
            && let Some((position, target)) = find_variable_arg_in_action(expr, id)
            && let Some(name) = get_variable_name(expr, target)
            && is_temp_var(name.as_str(), TEMP_PREFIXES)
        {
            actions_by_temp
                .entry(name.to_string())
                .or_default()
                .push((id, position));
        }
    }
    actions_by_temp
        .into_iter()
        .filter_map(|(name, actions)| (actions.len() == 1).then(|| (name, actions[0])))
        .collect()
}

fn collect_aliases(expr: &RecExpr<Mir>) -> AliasData {
    let mut data = AliasData {
        action_lets: HashMap::new(),
        aliases: HashMap::new(),
        reverse_aliases: HashMap::new(),
        alias_lets: HashMap::new(),
    };
    for (index, node) in expr.as_ref().iter().enumerate() {
        let id = Id::from(index);
        let Mir::Let([variable, value, _]) = node else {
            continue;
        };
        let Some(variable_name) = get_variable_name(expr, *variable)
            .filter(|name| is_temp_var(name.as_str(), TEMP_PREFIXES))
        else {
            continue;
        };
        if matches!(&expr[*value], Mir::Action(_)) {
            if action_writes_to(expr, *value, variable_name.as_str()) {
                data.action_lets.insert(variable_name.to_string(), id);
            }
            continue;
        }
        if let Some((alias_name, alias_id)) = extract_alias(expr, *value, variable_name.as_str()) {
            data.aliases
                .insert(variable_name.to_string(), (alias_name.clone(), alias_id));
            data.reverse_aliases
                .insert(alias_name, (variable_name.to_string(), *variable));
            data.alias_lets.insert(variable_name.to_string(), id);
        }
    }
    data
}

fn action_writes_to(expr: &RecExpr<Mir>, action: Id, expected: &str) -> bool {
    find_variable_arg_in_action(expr, action)
        .and_then(|(_, target)| get_variable_name(expr, target))
        .is_some_and(|name| name == expected.into())
}

fn extract_alias(expr: &RecExpr<Mir>, value: Id, outer_name: &str) -> Option<(String, Id)> {
    match &expr[value] {
        Mir::Let([variable, value, body]) if same_variable(expr, *variable, *body) => {
            if matches!(&expr[*value], Mir::Action(_)) {
                let (_, target) = find_variable_arg_in_action(expr, *value)?;
                let name = get_variable_name(expr, target)?;
                return (name.as_str() != outer_name && is_temp_var(name.as_str(), TEMP_PREFIXES))
                    .then(|| (name.to_string(), *value));
            }
            extract_block_alias(expr, *value, outer_name)
        }
        Mir::Block(_) => extract_block_alias(expr, value, outer_name),
        _ => None,
    }
}

fn extract_block_alias(expr: &RecExpr<Mir>, block: Id, outer_name: &str) -> Option<(String, Id)> {
    let Mir::Block(children) = &expr[block] else {
        return None;
    };
    let id = *children.last()?;
    let name = get_variable_name(expr, id)?;
    (name.as_str() != outer_name && is_temp_var(name.as_str(), TEMP_PREFIXES))
        .then(|| (name.to_string(), id))
}

fn collect_copies(expr: &RecExpr<Mir>) -> CopyData {
    let mut data = CopyData {
        copies: HashMap::new(),
        set_values: HashMap::new(),
        immediately_dead: HashSet::new(),
    };
    for index in 0..expr.as_ref().len() {
        let id = Id::from(index);
        let Some((target, value)) =
            extract_var_value_args(expr, id).filter(|_| is_pure_copy_action(expr, id))
        else {
            continue;
        };
        let target_name = get_variable_name(expr, target);
        let value_name = get_variable_name(expr, value);
        if same_variable(expr, target, value) {
            data.immediately_dead.insert(id);
            continue;
        }
        let source = match &expr[value] {
            Mir::Let([variable, _, body])
                if get_variable_name(expr, *variable) == get_variable_name(expr, *body) =>
            {
                get_variable_name(expr, *variable)
            }
            _ => value_name,
        };
        if let Some(source) = source.filter(|name| is_temp_var(name.as_str(), TEMP_PREFIXES))
            && let Some(target_name) = target_name
        {
            data.copies
                .insert(source.to_string(), (target_name.to_string(), target));
            data.set_values.insert(source.to_string(), id);
        }
    }
    let write_counts = collect_write_counts(expr);
    data.copies.retain(|source, (target, _)| {
        write_counts.get(target).copied().unwrap_or(0) == 1
            && write_counts.get(source).copied().unwrap_or(0) <= 1
    });
    data.set_values
        .retain(|source, _| data.copies.contains_key(source));
    data
}

fn resolve_chains(
    action_writes: &ActionWrites,
    aliases: &AliasData,
    copies: &CopyData,
) -> Resolution {
    let all_temps = copies
        .copies
        .keys()
        .chain(action_writes.keys())
        .chain(aliases.aliases.keys())
        .chain(aliases.reverse_aliases.keys())
        .cloned()
        .collect::<HashSet<_>>();
    let mut resolution = Resolution {
        redirects: HashMap::new(),
        dead_lets: HashSet::new(),
        dead_set_values: copies.immediately_dead.clone(),
        dead_temps: HashSet::new(),
    };
    for source in all_temps {
        resolve_chain(&source, aliases, copies, &mut resolution);
    }
    resolution
}

fn resolve_chain(
    source: &str,
    aliases: &AliasData,
    copies: &CopyData,
    resolution: &mut Resolution,
) {
    let mut current = source.to_owned();
    let mut visited = HashSet::from([current.clone()]);
    let mut targets = Vec::new();
    let mut dead_lets = HashSet::new();
    let mut dead_set_values = HashSet::new();
    loop {
        if let Some(&id) = aliases.action_lets.get(&current) {
            dead_lets.insert(id);
        }
        if let Some(&id) = aliases.alias_lets.get(&current) {
            dead_lets.insert(id);
        }
        if let Some(&id) = copies.set_values.get(&current) {
            dead_set_values.insert(id);
        }
        let next = copies
            .copies
            .get(&current)
            .or_else(|| aliases.reverse_aliases.get(&current));
        let Some((name, id)) = next.filter(|(name, _)| visited.insert(name.clone())) else {
            break;
        };
        current.clone_from(name);
        targets.push((name.clone(), *id));
    }
    let Some((target_name, target_id)) = targets.last() else {
        return;
    };
    resolution
        .redirects
        .insert(source.to_owned(), (target_name.clone(), *target_id));
    resolution.dead_lets.extend(dead_lets);
    resolution.dead_set_values.extend(dead_set_values);
    mark_dead_temps(source, aliases, copies, &mut resolution.dead_temps);
}

fn mark_dead_temps(
    source: &str,
    aliases: &AliasData,
    copies: &CopyData,
    dead_temps: &mut HashSet<String>,
) {
    let mut current = source.to_owned();
    let mut visited = HashSet::new();
    loop {
        if !visited.insert(current.clone()) {
            break;
        }
        dead_temps.insert(current.clone());
        let next = copies
            .copies
            .get(&current)
            .or_else(|| aliases.reverse_aliases.get(&current));
        let Some((name, _)) = next else {
            break;
        };
        current.clone_from(name);
    }
    dead_temps.remove(&current);
}

fn find_dead_lets(expr: &RecExpr<Mir>, resolution: &mut Resolution) {
    for (index, node) in expr.as_ref().iter().enumerate() {
        let id = Id::from(index);
        let Mir::Let([variable, _, body]) = node else {
            continue;
        };
        let Some(name) = get_variable_name(expr, *variable).filter(|name| {
            resolution.dead_temps.contains(name.as_str()) && !resolution.dead_lets.contains(&id)
        }) else {
            continue;
        };
        if resolution
            .redirects
            .get(name.as_str())
            .is_some_and(|(redirected, _)| !is_plain_temp(redirected.as_str(), TEMP_PREFIXES))
        {
            continue;
        }
        if resolution.dead_set_values.contains(body) || same_variable(expr, *variable, *body) {
            resolution.dead_lets.insert(id);
        }
    }
}

struct Rewriter<'a> {
    expr: &'a RecExpr<Mir>,
    redirects: &'a NamedTarget,
    dead_lets: &'a HashSet<Id>,
    dead_set_values: &'a HashSet<Id>,
    nodes: NodeArena<Mir>,
    id_map: Vec<Id>,
}

impl<'a> Rewriter<'a> {
    fn new(expr: &'a RecExpr<Mir>, resolution: &'a Resolution) -> Self {
        Self {
            expr,
            redirects: &resolution.redirects,
            dead_lets: &resolution.dead_lets,
            dead_set_values: &resolution.dead_set_values,
            nodes: NodeArena::with_capacity(expr.len()),
            id_map: vec![Id::from(0); expr.len()],
        }
    }

    fn rewrite(mut self) -> RecExpr<Mir> {
        for (index, node) in self.expr.as_ref().iter().enumerate() {
            let old_id = Id::from(index);
            let new_id = self.rewrite_node(old_id, node);
            self.id_map[index] = new_id;
        }
        let root = self.id_map[self.expr.as_ref().len() - 1];
        if !self.nodes.is_empty() && usize::from(root) != self.nodes.len() - 1 {
            let root_node = self.nodes.as_slice()[usize::from(root)].clone();
            self.nodes.add(root_node);
        }
        self.nodes.into_recexpr()
    }

    fn rewrite_node(&mut self, old_id: Id, node: &Mir) -> Id {
        if let Some(id) = self.redirected_variable(old_id) {
            return id;
        }
        if let Some(id) = self.rewrite_dead_let(old_id, node) {
            return id;
        }
        if self.dead_set_values.contains(&old_id) {
            return self.rewrite_dead_set(old_id);
        }
        if let Mir::Block(children) = node {
            return self.rewrite_block(children);
        }
        if let Some(id) = self.rewrite_action(node) {
            return id;
        }
        let mapped = node.clone().map_children(|child| self.mapped(child));
        self.nodes.add(mapped)
    }

    fn redirected_variable(&mut self, id: Id) -> Option<Id> {
        let name = get_variable_name(self.expr, id)?;
        let (_, target) = self.redirects.get(name.as_str())?;
        (name != get_variable_name(self.expr, *target).unwrap_or_else(|| Symbol::from("")))
            .then(|| clone_var_node(self.expr, *target, &mut self.nodes, &self.id_map))
    }

    fn rewrite_dead_let(&mut self, id: Id, node: &Mir) -> Option<Id> {
        let Mir::Let([variable, value, body]) = node else {
            return None;
        };
        if !self.dead_lets.contains(&id) {
            return None;
        }
        if same_variable(self.expr, *variable, *body) {
            return Some(self.mapped(*value));
        }
        let discard_value = is_pure_copy_action(self.expr, *value)
            && extract_var_value_args(self.expr, *value)
                .and_then(|(target, _)| get_variable_name(self.expr, target))
                .is_some_and(|target| !self.redirects.contains_key(target.as_str()));
        if discard_value {
            return Some(self.mapped(*body));
        }
        let value = self.mapped(*value);
        let body = self.mapped(*body);
        if matches!(self.nodes.as_slice()[usize::from(value)], Mir::Nop) {
            Some(body)
        } else {
            Some(self.nodes.add(Mir::Block(Box::new([value, body]))))
        }
    }

    fn rewrite_dead_set(&mut self, id: Id) -> Id {
        if let Some((_, value)) = extract_var_value_args(self.expr, id)
            && matches!(
                self.expr[value],
                Mir::Let(_) | Mir::Block(_) | Mir::Action(_)
            )
        {
            return self.mapped(value);
        }
        self.nodes.add(Mir::Nop)
    }

    fn rewrite_block(&mut self, children: &[Id]) -> Id {
        let mut retained = Vec::with_capacity(children.len());
        for &child in children {
            if self.dead_set_values.contains(&child) {
                let child = self.mapped(child);
                if !matches!(self.nodes.as_slice()[usize::from(child)], Mir::Nop) {
                    retained.push(child);
                }
                continue;
            }
            retained.push(self.mapped(child));
        }
        match retained.as_slice() {
            [] => self.nodes.add(Mir::Nop),
            [child] => *child,
            _ => self.nodes.add(Mir::Block(retained.into_boxed_slice())),
        }
    }

    fn rewrite_action(&mut self, node: &Mir) -> Option<Id> {
        let Mir::Action(ids) = node else {
            return None;
        };
        let Mir::List(args) = ids.get(3).map(|id| &self.expr[*id])? else {
            return None;
        };
        let mut new_args = Vec::with_capacity(args.len());
        let mut modified = false;
        for &arg in args {
            if let Some(rewritten) = self.rewrite_variable_arg(arg) {
                new_args.push(rewritten);
                modified = true;
            } else {
                new_args.push(self.mapped(arg));
            }
        }
        if !modified {
            return None;
        }
        let args = self.nodes.add(Mir::List(new_args.into_boxed_slice()));
        let ids = ids
            .iter()
            .enumerate()
            .map(|(index, id)| if index == 3 { args } else { self.mapped(*id) })
            .collect::<Vec<_>>();
        Some(self.nodes.add(Mir::Action(ids.into_boxed_slice())))
    }

    fn rewrite_variable_arg(&mut self, arg: Id) -> Option<Id> {
        let Mir::Named([name, value]) = &self.expr[arg] else {
            return None;
        };
        if !node_str_eq(&self.expr[*name], "variable") {
            return None;
        }
        let temp = get_variable_name(self.expr, *value)?;
        let (_, target) = self.redirects.get(temp.as_str())?;
        let variable = clone_var_node(self.expr, *target, &mut self.nodes, &self.id_map);
        let name = self.mapped(*name);
        Some(self.nodes.add(Mir::Named([name, variable])))
    }

    fn mapped(&self, id: Id) -> Id {
        self.id_map[usize::from(id)]
    }
}

fn coalesce_pass(expr: &RecExpr<Mir>) -> (RecExpr<Mir>, bool) {
    if expr.is_empty() {
        return (expr.clone(), false);
    }

    log::trace!("=== Copy Coalescing Start ===");
    log::trace!("Input expr ({} nodes): {expr:?}", expr.len());

    let action_writes = collect_action_writes(expr);
    let aliases = collect_aliases(expr);
    let copies = collect_copies(expr);
    let mut resolution = resolve_chains(&action_writes, &aliases, &copies);
    find_dead_lets(expr, &mut resolution);
    if resolution.redirects.is_empty()
        && resolution.dead_set_values.is_empty()
        && resolution.dead_lets.is_empty()
    {
        log::trace!("  No redirects or dead nodes found. Returning unchanged.");
        return (expr.clone(), false);
    }

    (Rewriter::new(expr, &resolution).rewrite(), true)
}

#[derive(Debug, Clone, Default)]
pub struct CopyCoalescingPass;

impl FunctionPass<Mir> for CopyCoalescingPass {
    const OPT_LEVEL: u8 = 2;

    fn run(&self, expr: &RecExpr<Mir>) -> RecExpr<Mir> {
        let mut current = expr.clone();
        loop {
            let (new_expr, changed) = coalesce_pass(&current);
            if !changed {
                break;
            }
            current = new_expr;
        }
        current
    }
}
