//! `jmcc.lock` dependency lockfile format and management.
//!
//! Captures exact package versions, sources (git commit SHAs, relative paths),
//! checksums, and dependency relationships for reproducible builds.

use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use tracing::debug;

use super::error::{ProjectError, Result};
use super::git::GitCache;
use super::manifest::Manifest;
use super::resolve::PackageGraph;

/// Lockfile representation (`jmcc.lock`).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Lockfile {
    /// Lockfile format version (currently 1).
    pub version: u32,
    /// Flat list of all locked packages in the dependency tree.
    #[serde(default, rename = "package")]
    pub packages: Vec<LockedPackage>,
}

/// Information about a single locked package.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockedPackage {
    /// Package name.
    pub name: String,
    /// Exact package version.
    pub version: String,
    /// Package source locator (`git+<url>?<ref>#<sha>` or `path+<path>`), if not the root package.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    /// Checksum (SHA-256) of package contents.
    pub checksum: Option<String>,
    /// List of direct dependency names.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependencies: Vec<String>,
}

impl Lockfile {
    /// Loads a `jmcc.lock` from a given file path.
    ///
    /// # Errors
    /// Returns error if file reading or TOML parsing fails.
    pub fn from_file(path: &Path) -> Result<Self> {
        let content = fs::read_to_string(path)?;
        Self::from_str(&content, path)
    }

    /// Parses a `jmcc.lock` from a string slice.
    ///
    /// # Errors
    /// Returns error if TOML deserialization fails.
    pub fn from_str(content: &str, path: &Path) -> Result<Self> {
        toml::from_str::<Self>(content).map_err(|source| ProjectError::LockfileParse {
            path: path.to_path_buf(),
            source,
        })
    }

    /// Serializes and writes this lockfile to disk with header comment.
    ///
    /// # Errors
    /// Returns error if serializing or file write fails.
    pub fn write_to_file(&self, path: &Path) -> Result<()> {
        let toml_str = toml::to_string_pretty(self)
            .map_err(|e| ProjectError::Generic(format!("Failed to serialize lockfile: {e}")))?;

        let formatted = format!(
            "# This file is automatically @generated by JMCC.\n# It is not intended for manual editing.\nversion = {}\n\n{}",
            self.version,
            // Strip any leading 'version = ...' if toml included it
            toml_str
                .strip_prefix(&format!("version = {}\n\n", self.version))
                .unwrap_or(&toml_str)
        );

        fs::write(path, formatted)?;
        debug!(path = %path.display(), "Wrote jmcc.lock");
        Ok(())
    }

    /// Finds a locked package by name.
    #[must_use]
    pub fn get_package(&self, name: &str) -> Option<&LockedPackage> {
        self.packages.iter().find(|p| p.name == name)
    }

    /// Generates a lockfile from root manifest, root directory, and resolved package graph.
    #[must_use]
    pub fn generate(root_manifest: &Manifest, root_dir: &Path, graph: &PackageGraph) -> Self {
        let mut packages = Vec::new();

        let root_name = root_manifest.name(root_dir).unwrap_or("root").to_owned();
        let root_version = root_manifest.version();
        let mut root_deps: Vec<String> = root_manifest
            .all_dependencies(true)
            .keys()
            .cloned()
            .collect();
        root_deps.sort();

        packages.push(LockedPackage {
            name: root_name,
            version: root_version,
            source: None,
            checksum: compute_package_checksum(root_dir),
            dependencies: root_deps,
        });

        for (name, pkg) in &graph.packages {
            let mut direct_deps = Vec::new();
            if let Some(man) = &pkg.manifest {
                direct_deps = man.dependencies.keys().cloned().collect();
                direct_deps.sort();
            }

            let source = Some(determine_package_source(pkg, root_dir));
            let checksum = compute_package_checksum(&pkg.root_dir);

            packages.push(LockedPackage {
                name: name.clone(),
                version: pkg.version.clone(),
                source,
                checksum,
                dependencies: direct_deps,
            });
        }

        Self {
            version: 1,
            packages,
        }
    }

    /// Validates that this lockfile is consistent with the manifest dependencies.
    ///
    /// # Errors
    /// Returns `ProjectError::LockfileOutOfDate` if dependencies differ or are missing.
    pub fn validate_against_manifest(
        &self,
        root_manifest: &Manifest,
        root_dir: &Path,
        include_dev: bool,
    ) -> Result<()> {
        let manifest_deps = root_manifest.all_dependencies(include_dev);

        for (dep_name, dep) in &manifest_deps {
            let locked = self.get_package(dep_name).ok_or_else(|| {
                ProjectError::LockfileOutOfDate {
                    path: root_dir.join("jmcc.lock"),
                    reason: format!(
                        "Dependency '{dep_name}' is declared in jmcc.toml but missing in jmcc.lock"
                    ),
                }
            })?;

            let detailed = dep.detailed();

            // Check version constraint if specified
            if let Some(req_ver) = &detailed.version
                && req_ver != &locked.version
            {
                return Err(ProjectError::LockfileOutOfDate {
                    path: root_dir.join("jmcc.lock"),
                    reason: format!(
                        "Dependency '{dep_name}' version mismatch: manifest requested '{req_ver}', lockfile has '{}'",
                        locked.version
                    ),
                });
            }

            // Check git url if git dependency
            if let Some(git_url) = &detailed.git {
                let Some(source) = &locked.source else {
                    return Err(ProjectError::LockfileOutOfDate {
                        path: root_dir.join("jmcc.lock"),
                        reason: format!(
                            "Dependency '{dep_name}' is a git dependency in manifest, but has no source in lockfile"
                        ),
                    });
                };
                if !source.starts_with("git+") || !source.contains(git_url.as_str()) {
                    return Err(ProjectError::LockfileOutOfDate {
                        path: root_dir.join("jmcc.lock"),
                        reason: format!("Dependency '{dep_name}' git url changed to '{git_url}'"),
                    });
                }
            }
        }

        Ok(())
    }
}

fn determine_package_source(pkg: &super::resolve::ResolvedPackage, root_dir: &Path) -> String {
    // Check if git checkout
    if (pkg.root_dir.join(".git").exists()
        || pkg
            .root_dir
            .to_string_lossy()
            .contains("/.jmcc/cache/git/checkouts/"))
        && let Ok(sha) = GitCache::head_commit(&pkg.root_dir)
    {
        return format!("git+#{sha}");
    }

    // Relative path dependency
    if let Ok(rel) = pkg.root_dir.strip_prefix(root_dir) {
        return format!("path+{}", rel.display());
    }

    // Otherwise standard path
    format!("path+{}", pkg.root_dir.display())
}

/// Computes a deterministic SHA-256 checksum over key source files of a package.
#[must_use]
pub fn compute_package_checksum(dir: &Path) -> Option<String> {
    let mut files_to_hash = Vec::new();
    let manifest_path = dir.join("jmcc.toml");
    if manifest_path.is_file() {
        files_to_hash.push(manifest_path);
    }

    let src_dir = dir.join("src");
    if src_dir.is_dir() {
        collect_jc_files(&src_dir, &mut files_to_hash);
    } else {
        collect_jc_files(dir, &mut files_to_hash);
    }

    if files_to_hash.is_empty() {
        return None;
    }

    files_to_hash.sort();

    let mut hasher = Sha256::new();
    for f in &files_to_hash {
        let rel = f.strip_prefix(dir).unwrap_or(f);
        hasher.update(rel.to_string_lossy().as_bytes());
        if let Ok(bytes) = fs::read(f) {
            hasher.update(&bytes);
        }
    }

    Some(format!("sha256:{}", hasher.finalize_hex()))
}

fn collect_jc_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let p = entry.path();
        if p.is_dir() {
            let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
            if !name.starts_with('.') && name != "target" && name != "tests" {
                collect_jc_files(&p, out);
            }
        } else if p.is_file() && p.extension().and_then(|e| e.to_str()) == Some("jc") {
            out.push(p);
        }
    }
}

// ---------------------------------------------------------------------------
// Standalone pure-Rust SHA-256 implementation (FIPS 180-4 standard)
// ---------------------------------------------------------------------------

struct Sha256 {
    state: [u32; 8],
    count: u64,
    buffer: [u8; 64],
}

impl Sha256 {
    const K: [u32; 64] = [
        0x428a_2f98,
        0x7137_4491,
        0xb5c0_fbcf,
        0xe9b5_dba5,
        0x3956_c25b,
        0x59f1_11f1,
        0x923f_82a4,
        0xab1c_5ed5,
        0xd807_aa98,
        0x1283_5b01,
        0x2431_85be,
        0x550c_7dc3,
        0x72be_5d74,
        0x80de_b1fe,
        0x9bdc_06a7,
        0xc19b_f174,
        0xe49b_69c1,
        0xefbe_4786,
        0x0fc1_9dc6,
        0x240c_a1cc,
        0x2de9_2c6f,
        0x4a74_84aa,
        0x5cb0_a9dc,
        0x76f9_88da,
        0x983e_5152,
        0xa831_c66d,
        0xb003_27c8,
        0xbf59_7fc7,
        0xc6e0_0bf3,
        0xd5a7_9147,
        0x06ca_6351,
        0x1429_2967,
        0x27b7_0a85,
        0x2e1b_2138,
        0x4d2c_6dfc,
        0x5338_0d13,
        0x650a_7354,
        0x766a_0abb,
        0x81c2_c92e,
        0x9272_2c85,
        0xa2bf_e8a1,
        0xa81a_664b,
        0xc24b_8b70,
        0xc76c_51a3,
        0xd192_e819,
        0xd699_0624,
        0xf40e_3585,
        0x106a_a070,
        0x19a4_c116,
        0x1e37_6c08,
        0x2748_774c,
        0x34b0_bcb5,
        0x391c_0cb3,
        0x4ed8_aa4a,
        0x5b9c_ca4f,
        0x682e_6ff3,
        0x748f_82ee,
        0x78a5_636f,
        0x84c8_7814,
        0x8cc7_0208,
        0x90be_fffa,
        0xa450_6ceb,
        0xbef9_a3f7,
        0xc671_78f2,
    ];

    const fn new() -> Self {
        Self {
            state: [
                0x6a09_e667,
                0xbb67_ae85,
                0x3c6e_f372,
                0xa54f_f53a,
                0x510e_527f,
                0x9b05_688c,
                0x1f83_d9ab,
                0x5be0_cd19,
            ],
            count: 0,
            buffer: [0u8; 64],
        }
    }

    fn update(&mut self, mut input: &[u8]) {
        let mut idx = (self.count & 63) as usize;
        self.count = self.count.wrapping_add(input.len() as u64);

        if idx > 0 && idx + input.len() >= 64 {
            let needed = 64 - idx;
            self.buffer[idx..64].copy_from_slice(&input[..needed]);
            Self::transform(&mut self.state, &self.buffer);
            input = &input[needed..];
            idx = 0;
        }

        while input.len() >= 64 {
            Self::transform(&mut self.state, &input[..64]);
            input = &input[64..];
        }

        if !input.is_empty() {
            self.buffer[idx..idx + input.len()].copy_from_slice(input);
        }
    }

    fn finalize(mut self) -> [u8; 32] {
        let bit_len = self.count.wrapping_mul(8);
        let idx = (self.count & 63) as usize;
        let pad_len = if idx < 56 { 56 - idx } else { 120 - idx };

        let mut padding = [0u8; 120];
        padding[0] = 0x80;
        self.update(&padding[..pad_len]);
        self.update(&bit_len.to_be_bytes());

        let mut digest = [0u8; 32];
        for (i, word) in self.state.iter().enumerate() {
            digest[i * 4..(i + 1) * 4].copy_from_slice(&word.to_be_bytes());
        }
        digest
    }

    fn finalize_hex(self) -> String {
        const HEX_CHARS: &[u8; 16] = b"0123456789abcdef";
        let digest = self.finalize();
        let mut s = String::with_capacity(64);
        for b in digest {
            s.push(HEX_CHARS[(b >> 4) as usize] as char);
            s.push(HEX_CHARS[(b & 0x0f) as usize] as char);
        }
        s
    }

    #[expect(
        clippy::many_single_char_names,
        clippy::needless_range_loop,
        reason = "standard cryptographic notation and indexing"
    )]
    fn transform(state: &mut [u32; 8], block: &[u8]) {
        let mut w = [0u32; 64];
        for i in 0..16 {
            w[i] = u32::from_be_bytes([
                block[i * 4],
                block[i * 4 + 1],
                block[i * 4 + 2],
                block[i * 4 + 3],
            ]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }

        let mut a = state[0];
        let mut b = state[1];
        let mut c = state[2];
        let mut d = state[3];
        let mut e = state[4];
        let mut f = state[5];
        let mut g = state[6];
        let mut h = state[7];

        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ ((!e) & g);
            let temp1 = h
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(Self::K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let temp2 = s0.wrapping_add(maj);

            h = g;
            g = f;
            f = e;
            e = d.wrapping_add(temp1);
            d = c;
            c = b;
            b = a;
            a = temp1.wrapping_add(temp2);
        }

        state[0] = state[0].wrapping_add(a);
        state[1] = state[1].wrapping_add(b);
        state[2] = state[2].wrapping_add(c);
        state[3] = state[3].wrapping_add(d);
        state[4] = state[4].wrapping_add(e);
        state[5] = state[5].wrapping_add(f);
        state[6] = state[6].wrapping_add(g);
        state[7] = state[7].wrapping_add(h);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sha256_known_vectors() {
        // Empty string
        let h1 = Sha256::new().finalize_hex();
        assert_eq!(
            h1,
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );

        // "abc"
        let mut hasher2 = Sha256::new();
        hasher2.update(b"abc");
        assert_eq!(
            hasher2.finalize_hex(),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
    }

    #[test]
    fn test_lockfile_roundtrip() {
        let lock = Lockfile {
            version: 1,
            packages: vec![
                LockedPackage {
                    name: "root_pkg".to_owned(),
                    version: "1.0.0".to_owned(),
                    source: None,
                    checksum: Some("sha256:abcd".to_owned()),
                    dependencies: vec!["dep_a".to_owned()],
                },
                LockedPackage {
                    name: "dep_a".to_owned(),
                    version: "0.2.0".to_owned(),
                    source: Some("path+../dep_a".to_owned()),
                    checksum: None,
                    dependencies: vec![],
                },
            ],
        };

        let toml_str = toml::to_string_pretty(&lock).unwrap();
        let parsed = Lockfile::from_str(&toml_str, Path::new("jmcc.lock")).unwrap();
        assert_eq!(lock, parsed);
    }
}
